name: Sync LeetCode

on:
  workflow_dispatch: # Allows you to click a button to run it manually
  schedule:
    - cron: "0 8 * * *" # Runs automatically every day at 8am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: automated-solutions
          verbose: true
          commit-header: '[LeetCode Sync]'

